exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  ManualDispatch:
    exclude:
      - Wholeable::Builder#coalesce_members
  NestedIterators:
    exclude:
      - Wholeable::Builder#define_diff
  TooManyStatements:
    exclude:
      - Wholeable::Builder#define_diff
      - Wholeable::Builder#define_inspect
